run:
  skip-files:
    - export_test.go
linters-settings:
  goimports:
    local-prefixes: github.com/ShintaNakama/csv_parse

linters:
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused
